# Generated by Django 4.2.6 on 2023-10-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxcdron_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='number_of_free_drones',
        ),
        migrations.AddField(
            model_name='places',
            name='all_drones_id',
            field=models.ManyToManyField(to='zxcdron_app.drone'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_is_free',
            field=models.CharField(choices=[('Занят', 'Busy'), ('Свободен', 'Free')], default='Свободен', max_length=9),
        ),
        migrations.AlterField(
            model_name='drone',
            name='power',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight',
            field=models.CharField(max_length=30),
        ),
    ]
