# Generated by Django 4.2.6 on 2023-10-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zxcdron_app', '0003_drone_dron_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='dron_type',
            new_name='drone_type',
        ),
    ]
