# Generated by Django 4.2.6 on 2023-10-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxcdron_app', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_and_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
