# Generated by Django 4.2.6 on 2023-10-27 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxcdron_app', '0011_order_used_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default='1111-11-11 11:11'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zxcdron_app.places')),
            ],
        ),
    ]
