# Generated by Django 4.2.6 on 2023-10-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxcdron_app', '0014_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(default='1111-11-11 11:11', max_length=15),
        ),
    ]
