# Generated by Django 4.2.6 on 2023-10-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxcdron_app', '0002_remove_places_number_of_free_drones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='dron_type',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=7),
        ),
    ]
