# Generated by Django 4.2.6 on 2023-10-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxcdron_app', '0008_remove_order_order_id_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zxcdron_app.places')),
            ],
        ),
    ]
