# Generated by Django 4.2.6 on 2023-10-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxcdron_app', '0010_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='used_places',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='zxcdron_app.places'),
        ),
    ]
